import { readFileSync } from 'node:fs';
import path from 'node:path';
import {
  buildMockOffers,
  buildFixtureRecipes,
  getIngredientNutrition,
  MOCK_PRICE_SOURCE_LABEL,
  STORES,
} from './fixtures';
import type {
  NutritionPer100g,
  ProductOffer,
  Recipe,
  Store,
  StoreId,
} from './types';

/**
 * Provider abstractions. New data sources plug in here without touching the
 * business logic:
 *   - RecipeProvider: where recipes come from. Fixture demo catalog is the
 *     fallback for local development; the default is the offline recipe
 *     catalogue snapshot (backend/menu-data/recipes.json), used by the
 *     deterministic menu fallback. In the request path recipes are normally
 *     generated by the AI planner (see services/menu/aiMenu.ts).
 *   - PriceProvider: per-store product offers. Mock demo data is the fallback;
 *     the default is the curated snapshot of real retail catalogue prices
 *     (backend/menu-data/prices.json, produced by
 *     backend/scripts/crawl-prices.ts and/or maintained by a human curator).
 *   - NutritionProvider: per-100g reference values computed from our curated
 *     ingredient nutrition DB (reference tables, e.g. USDA style averages).
 *     Recipe pages do not publish per-recipe kcal/BJXY, so nutrition is always
 *     computed from the ingredient DB for real recipes too.
 */

const MENU_DATA_DIR = path.join(process.cwd(), 'menu-data');

export interface RecipeProvider {
  readonly kind: string;
  getAllRecipes(): Promise<Recipe[]>;
  getRecipe(id: string): Promise<Recipe | null>;
}

export interface PriceProvider {
  readonly kind: string;
  readonly isMock: boolean;
  /** Human-readable provenance of the numbers, e.g. harness + date. */
  readonly sourceLabel: string;
  getStores(): Promise<Store[]>;
  getOffers(storeId: StoreId): Promise<ProductOffer[]>;
}

export interface NutritionProvider {
  /** Per-100g values for the ingredient, or null when unknown. */
  getPer100g(ingredientId: string, ingredientName: string): Promise<NutritionPer100g | null>;
  readonly sourceLabel: string;
}

// ---------------------------------------------------------------------------
// Fixture / demo providers
// ---------------------------------------------------------------------------

export class FixtureRecipeProvider implements RecipeProvider {
  readonly kind = 'fixture';
  private readonly recipes = buildFixtureRecipes();

  getAllRecipes(): Promise<Recipe[]> {
    return Promise.resolve(this.recipes);
  }

  getRecipe(id: string): Promise<Recipe | null> {
    return Promise.resolve(this.recipes.find((r) => r.id === id) ?? null);
  }
}

export class MockPriceProvider implements PriceProvider {
  readonly kind = 'mock';
  readonly isMock = true;
  private readonly offers = buildMockOffers();
  readonly sourceLabel = MOCK_PRICE_SOURCE_LABEL;

  getStores(): Promise<Store[]> {
    return Promise.resolve(STORES);
  }

  getOffers(storeId: StoreId): Promise<ProductOffer[]> {
    return Promise.resolve(this.offers.filter((o) => o.storeId === storeId));
  }
}

export class FixtureNutritionProvider implements NutritionProvider {
  readonly sourceLabel = 'Справочная база пищевой ценности';

  getPer100g(ingredientId: string, _ingredientName: string): Promise<NutritionPer100g | null> {
    return Promise.resolve(getIngredientNutrition(ingredientId));
  }
}

// ---------------------------------------------------------------------------
// Real-data snapshot providers (backend/menu-data/*.json)
// ---------------------------------------------------------------------------

/** On-disk format of backend/menu-data/recipes.json (imported recipe catalogue). */
export interface RecipesSnapshotFile {
  kind: 'snapshot' | 'russianfood_import';
  fetchedAt: string;
  source: string;
  recipes: Recipe[];
}

/** On-disk format of backend/menu-data/prices.json (curated price snapshot). */
export interface PricesSnapshotFile {
  kind: 'snapshot';
  updatedAt: string;
  sourceName: string;
  /** Optional human-readable note per store, e.g. catalogue page used. */
  storeNotes?: Partial<Record<StoreId, string>>;
  offers: ProductOffer[];
}

function readJsonFile<T>(filePath: string): T | null {
  try {
    return JSON.parse(readFileSync(filePath, 'utf8')) as T;
  } catch {
    return null;
  }
}

/**
 * Offline recipe catalogue snapshot (backend/menu-data/recipes.json). Used as
 * the fallback recipe source for the deterministic planner. Falls back to an
 * empty catalogue when the snapshot is missing — the planner then reports
 * 'no_recipes'.
 */
export class SnapshotRecipeProvider implements RecipeProvider {
  readonly kind = 'snapshot';
  readonly sourceLabel = 'Локальный каталог рецептов';
  private readonly recipes: Recipe[];
  readonly snapshotMeta: { fetchedAt: string; source: string } | null;

  constructor(filePath = path.join(MENU_DATA_DIR, 'recipes.json')) {
    const parsed = readJsonFile<RecipesSnapshotFile>(filePath);
    if (parsed && Array.isArray(parsed.recipes)) {
      this.recipes = parsed.recipes;
      this.snapshotMeta = { fetchedAt: parsed.fetchedAt, source: parsed.source };
    } else {
      this.recipes = [];
      this.snapshotMeta = null;
    }
  }

  /** true when a usable snapshot is present on disk. */
  get isAvailable(): boolean {
    return this.recipes.length > 0;
  }

  getAllRecipes(): Promise<Recipe[]> {
    return Promise.resolve(this.recipes);
  }

  getRecipe(id: string): Promise<Recipe | null> {
    return Promise.resolve(this.recipes.find((r) => r.id === id) ?? null);
  }
}

/**
 * Real price snapshot of the retail chains' public catalogues. The numbers are
 * NOT scraped in the request path: they come from backend/menu-data/prices.json
 * which a human curator maintains (with the crawler tool as a helper). Every
 * offer carries isMock: false and its source; staleness is handled by the
 * planner via PRICE_MAX_AGE_DAYS.
 */
export class CuratedPriceProvider implements PriceProvider {
  readonly kind = 'snapshot';
  readonly isMock = false;
  private readonly offers: ProductOffer[];
  readonly snapshotMeta: { updatedAt: string; sourceName: string; storeNotes: Partial<Record<StoreId, string>> };
  readonly sourceLabel: string;

  constructor(filePath = path.join(MENU_DATA_DIR, 'prices.json')) {
    const parsed = readJsonFile<PricesSnapshotFile>(filePath);
    if (parsed && Array.isArray(parsed.offers)) {
      this.offers = parsed.offers;
      this.snapshotMeta = {
        updatedAt: parsed.updatedAt,
        sourceName: parsed.sourceName,
        storeNotes: parsed.storeNotes ?? {},
      };
      this.sourceLabel = `Реальные цены из каталогов сетей (${parsed.updatedAt})`;
    } else {
      this.offers = [];
      this.snapshotMeta = { updatedAt: '', sourceName: 'snapshot missing', storeNotes: {} };
      this.sourceLabel = 'Снапшот цен не найден';
    }
  }

  get isAvailable(): boolean {
    return this.offers.length > 0;
  }

  getStores(): Promise<Store[]> {
    return Promise.resolve(
      STORES.map((s) => (this.isAvailable ? { ...s, priceCatalog: 'live' } : s))
    );
  }

  getOffers(storeId: StoreId): Promise<ProductOffer[]> {
    return Promise.resolve(this.offers.filter((o) => o.storeId === storeId));
  }
}

/** Default provider bundle used by the planner. */
export interface MenuProviders {
  recipes: RecipeProvider;
  prices: PriceProvider;
  nutrition: NutritionProvider;
}

// Lazily-initialised singletons: snapshots are read from disk once.
let cachedPrices: CuratedPriceProvider | null = null;
let cachedRecipes: SnapshotRecipeProvider | null = null;

function priceProvider(): PriceProvider {
  if (!cachedPrices) cachedPrices = new CuratedPriceProvider();
  return cachedPrices.isAvailable ? cachedPrices : new MockPriceProvider();
}

function recipeProvider(): RecipeProvider {
  if (!cachedRecipes) cachedRecipes = new SnapshotRecipeProvider();
  return cachedRecipes.isAvailable ? cachedRecipes : new FixtureRecipeProvider();
}

export function defaultProviders(): MenuProviders {
  return {
    recipes: recipeProvider(),
    prices: priceProvider(),
    nutrition: new FixtureNutritionProvider(),
  };
}